name: PlatformIO CI

on:
  push:
   branches:
     - master
   tags:
     - build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        npm install html-minifier
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO firmware
      run: platformio run

    - name: Build the SPIFFS filesystem
      run: platformio run -t buildfs

    - name: Run PlatformIO check
      run: platformio check

    - name: Make artifacts
      run: |
        mkdir -p zip
        cd .pio/build
        for i in */spiffs.bin; do mv $i $(dirname $i)/erfs.bin; done
        zip ../../zip/wifinfo-$(git describe).zip $(ls */spiffs.bin */firmware.bin)

        tools/mkarduinosrc.py -1 arduino.zip

    - name: Archive firmware+spiffs
      uses: actions/upload-artifact@v1
      with:
        name: firmware-filesystem-arduino
        path: zip/
