name: PlatformIO CI

on:
  push:
   branches:
     - master
   tags:
     - build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo npm install -g html-minifier
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO firmware
      run: platformio run

    - name: Build the SPIFFS filesystem
      run: platformio run -t buildfs

    - name: Run PlatformIO check
      run: platformio check

    - name: Make artifacts
      run: |
        cd .pio/build
        mkdir -p ../zip
        zip ../zip/wifinfo-$(git describe).zip $(ls */spiffs.bin */firmware.bin)

    - name: Archive firmware+spiffs
      uses: actions/upload-artifact@v1
      with:
        name: firmware-spiffs
        path: .pio/zip/
