name: Unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Configure system
      run: |
        sudo apt-get install -y libgtest-dev python3 python3-pip xsltproc
        pip3 install -U setuptools
        pip3 install -U gcovr cpp-coveralls
        wget -nv -P test/support/nlohmann/ https://github.com/nlohmann/json/releases/download/v3.7.3/json.hpp

    - name: Build
      run: |
        set -x
        mkdir -p build artifacts
        cd build
        cmake -DCODE_COVERAGE=ON ..
        make -j
        ./tic --gtest_output=xml
        cd ..
        wget -nv https://github.com/adarmalik/gtest2html/raw/master/gtest2html.xslt
        xsltproc gtest2html.xslt build/test_detail.xml > artifacts/test_detail.html
        gcovr -r . --html -o artifacts/coverage.html

    - name: Archive tests and code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: tests-code-coverage-results
        path: artifacts/

    - name: Upload to coveralls.io
      run: |
        cpp-coveralls --exclude build --exclude .pio
      env:
        COVERALLS_REPO_TOKEN: oPNFisk0VZdO2ngxTczKuBnCI9Ms3kxYB
