name: Unit tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: configure system
      run: |
        sudo apt-get install -y libgtest-dev python3 python3-pip
        pip3 install -U gcovr
        wget -nv -P test/support/nlohmann/ https://github.com/nlohmann/json/releases/download/v3.7.3/json.hpp

    - name: build
      run: |
        mkdir -p build
        cd build
        cmake -DCODE_COVERAGE=ON ..
        make -j
        mkdir -p artifacts

    - name: test
      run: |
        ./tic

    - name: reports
      run: |
        wget -nv https://github.com/adarmalik/gtest2html/raw/master/gtest2html.xslt
        xsltproc gtest2html.xslt test_detail.xml > artifacts/test_detail.html
        gcovr -r .. --html -o artifacts/coverage.html

    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: build/artifacts/
